name: Validate Pull Request

on: [pull_request]

jobs:
  build_linux:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Install tools for compiling c++ files
        run: sudo apt install build-essential

      - name: Check compiler version
        run: g++ --version

      - name: Run Tests
        run: ./run_tests.sh
  

  build_macos:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v3

      - uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: '13.2.1'

      - name: Check compiler version
        run: g++ --version

      - name: Run Tests
        run: ./run_tests.sh
